### ISSUE TITLE
Leverage official mixpanel-php lib

### ISSUE THREAD

**Issue by patcon** [noahm/CakePHP-Mixpanel#8]
https://github.com/mixpanel/mixpanel-php
https://packagist.org/packages/mixpanel/mixpanel-php

If it doesn't cover your needs, I'm sure they'd appreciate the feedback :)

**Comment by patcon** [comment]
cc: @zippykid, who is hosting a wp plugin, but whose [github repo](https://github.com/zippykid/mixpanel-wordpress) lacks an issue queue

**Comment by noahm** [comment]
From [Mixpanel's PHP library documentation](https://mixpanel.com/help/reference/php):

> The Mixpanel PHP library is designed to be used for scripting, or in circumstances when a client can't or won't run client side scripts.
> 
> Mixpanel also provides a powerful and easy to use client-side JavaScript library for web applications. This library offers platform-specific features and conveniences that can make Mixpanel implementations much simpler, and can scale naturally to an unlimited number of clients. **The client-side JavaScript library is the preferred way to add Mixpanel to user-facing web applications.**

(emphasis mine)

**Comment by patcon** [comment]
:+1: Thanks and apologies on my skimming
